/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAlertasRouteImport } from './routes/_authenticated/app.alertas'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppCustosRouteImport } from './routes/_authenticated/app.custos'
import { Route as AuthenticatedAppInsumosRouteImport } from './routes/_authenticated/app.insumos'
import { Route as AuthenticatedAppMetasRouteImport } from './routes/_authenticated/app.metas'
import { Route as AuthenticatedAppProdutosRouteImport } from './routes/_authenticated/app.produtos'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppServicosRouteImport } from './routes/_authenticated/app.servicos'
import { Route as AuthenticatedAppSimuladoresRouteImport } from './routes/_authenticated/app.simuladores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAlertasRoute = AuthenticatedAppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustosRoute = AuthenticatedAppCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInsumosRoute = AuthenticatedAppInsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMetasRoute = AuthenticatedAppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProdutosRoute =
  AuthenticatedAppProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppServicosRoute =
  AuthenticatedAppServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSimuladoresRoute =
  AuthenticatedAppSimuladoresRouteImport.update({
    id: '/simuladores',
    path: '/simuladores',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/alertas': typeof AuthenticatedAppAlertasRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/custos': typeof AuthenticatedAppCustosRoute
  '/app/insumos': typeof AuthenticatedAppInsumosRoute
  '/app/metas': typeof AuthenticatedAppMetasRoute
  '/app/produtos': typeof AuthenticatedAppProdutosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/app/simuladores': typeof AuthenticatedAppSimuladoresRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/app/alertas': typeof AuthenticatedAppAlertasRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/custos': typeof AuthenticatedAppCustosRoute
  '/app/insumos': typeof AuthenticatedAppInsumosRoute
  '/app/metas': typeof AuthenticatedAppMetasRoute
  '/app/produtos': typeof AuthenticatedAppProdutosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/app/simuladores': typeof AuthenticatedAppSimuladoresRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/alertas': typeof AuthenticatedAppAlertasRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/custos': typeof AuthenticatedAppCustosRoute
  '/_authenticated/app/insumos': typeof AuthenticatedAppInsumosRoute
  '/_authenticated/app/metas': typeof AuthenticatedAppMetasRoute
  '/_authenticated/app/produtos': typeof AuthenticatedAppProdutosRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/servicos': typeof AuthenticatedAppServicosRoute
  '/_authenticated/app/simuladores': typeof AuthenticatedAppSimuladoresRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/recuperar-senha'
    | '/app'
    | '/app/alertas'
    | '/app/configuracoes'
    | '/app/custos'
    | '/app/insumos'
    | '/app/metas'
    | '/app/produtos'
    | '/app/relatorios'
    | '/app/servicos'
    | '/app/simuladores'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/recuperar-senha'
    | '/app/alertas'
    | '/app/configuracoes'
    | '/app/custos'
    | '/app/insumos'
    | '/app/metas'
    | '/app/produtos'
    | '/app/relatorios'
    | '/app/servicos'
    | '/app/simuladores'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/recuperar-senha'
    | '/_authenticated/app'
    | '/_authenticated/app/alertas'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/custos'
    | '/_authenticated/app/insumos'
    | '/_authenticated/app/metas'
    | '/_authenticated/app/produtos'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/servicos'
    | '/_authenticated/app/simuladores'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alertas': {
      id: '/_authenticated/app/alertas'
      path: '/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AuthenticatedAppAlertasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/custos': {
      id: '/_authenticated/app/custos'
      path: '/custos'
      fullPath: '/app/custos'
      preLoaderRoute: typeof AuthenticatedAppCustosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/insumos': {
      id: '/_authenticated/app/insumos'
      path: '/insumos'
      fullPath: '/app/insumos'
      preLoaderRoute: typeof AuthenticatedAppInsumosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/metas': {
      id: '/_authenticated/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AuthenticatedAppMetasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/produtos': {
      id: '/_authenticated/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AuthenticatedAppProdutosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/servicos': {
      id: '/_authenticated/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AuthenticatedAppServicosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/simuladores': {
      id: '/_authenticated/app/simuladores'
      path: '/simuladores'
      fullPath: '/app/simuladores'
      preLoaderRoute: typeof AuthenticatedAppSimuladoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAlertasRoute: typeof AuthenticatedAppAlertasRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppCustosRoute: typeof AuthenticatedAppCustosRoute
  AuthenticatedAppInsumosRoute: typeof AuthenticatedAppInsumosRoute
  AuthenticatedAppMetasRoute: typeof AuthenticatedAppMetasRoute
  AuthenticatedAppProdutosRoute: typeof AuthenticatedAppProdutosRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppServicosRoute: typeof AuthenticatedAppServicosRoute
  AuthenticatedAppSimuladoresRoute: typeof AuthenticatedAppSimuladoresRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAlertasRoute: AuthenticatedAppAlertasRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppCustosRoute: AuthenticatedAppCustosRoute,
  AuthenticatedAppInsumosRoute: AuthenticatedAppInsumosRoute,
  AuthenticatedAppMetasRoute: AuthenticatedAppMetasRoute,
  AuthenticatedAppProdutosRoute: AuthenticatedAppProdutosRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppServicosRoute: AuthenticatedAppServicosRoute,
  AuthenticatedAppSimuladoresRoute: AuthenticatedAppSimuladoresRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
